### PR TITLE
Added help labels to the predicted sequence metrics.

### PR DESCRIPTION
**Pull request by oliveramds**
Still subject to change. 

Charge:

- "The overall electric charge of the protein"

Isoelectric Point:

- "The pH at which this protein has no electrical charge"

Molecular Weight:

- "The sum of all atomic masses in the molecule"

Mol. Ext. Coeff. @ 280 nm:

- "The strength the protein absorbs light at 280nm"

### CODE REVIEW

**Comment by universvm** [comment]
Hi @oliveramds ,

Have you looked at the functions from AMPAL that calculate these metrics? There may be details you can add (eg. pH).

I see that you define several variables. Have you tried running the UI and see if it works? Can you post screenshots?

**Comment by oliveramds** [comment]
Hi @universvm, I haven't yet looked at the functions on AMPAL, thank you for pointing it out. I'll take a look :) 

Here are the screenshots using **1qys**: 

- Help icons next to column metric titles
image

- Charge:
image

- pI:
image

- Molec Weight:
image

- Mol ext:
image

**Comment by universvm** [comment]
Thanks looks good! Maybe we need to specify that it is the designed protein vs the real one (wrt "this protein").

**Comment by oliveramds** [comment]
St.image does not support gifs. Had to import additional modules: st.components and base64 to open the gif file locally. Added gif_container as an empty st element, which is populated by the function _draw_gif with a div containing a gif, and is cleared upon starting the app after the button is clicked. Due to the gif’s size (27MB), it takes a few seconds to load. It also takes a few seconds to reload after the user selects a file because Streamlit has to re-render the whole page in its new appearance.

I would recommend using a video file because:
- the use of video files is supported natively by streamlit
- an mp4 or webm or similar would likely be at most a tenth of the size
- it would load much, much more quickly.

image

**Comment by universvm** [comment]
Closed as stale request. Will need to be updated before merging.

**Pull request closed without merging**
