### PR TITLE
Multichainfix

### PR DESCRIPTION
**Pull request by sunal1996**
At the moment, if we want to predict sequences for a multi chain structure, TIMED merges the predictions for the individual chains and outputs a single chained fasta file. 

For instance, for a protein containing 184 aa in chain A and 184 aa in chain B, we would like to obtain a fasta file that contains the prediction for chain A with 184 aa and chain B with 184. However, at the moment, we are only getting a chain A as output and the length is 368. This PR aims to fix that.

### CODE REVIEW

**Comment by universvm** [comment]
Hey Mert LGTM - I will test it out hopefully tomorrow to see if the UI works. Does your example work with the current code?

**Comment by sunal1996** [comment]
> Hey Mert (@sunal1996 ) LGTM - I will test it out hopefully tomorrow to see if the UI works. Does your example work with the current code?

Yes, it did work for 3w8o + 3qy1 put together. Both are two chain proteins

**Comment by sunal1996** [comment]
To see if customization of pdb file names effect the code, I changed 3w8o.pdb to baba123_dubu_dib_co_212.pdb and it worked

**Comment by universvm** [comment]
Confirmed bug was fixed and different chains are displayed separately as they should. Had to modify the UI slighly
Screenshot 2024-05-06 at 15 31 17

Screenshot 2024-05-06 at 15 31 04

**Review by universvm — APPROVED** [review]
LGTM

**Pull request merged**
